#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run test
echo "🧪 Running tests..."
npm run test:run

#  $? 0 pass ✅ else fail ❌
if [ $? -eq 0 ]; then
  echo "✅ Tests passed! Running lint-staged..."
  npx lint-staged
else
  echo "❌ Tests failed! Commit aborted."
  exit 1
fi
